---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    ssl_verify_mode: :verify_peer

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    driver:
      network:
        - ["private_network", {ip: "10.10.10.20"}]
    run_list:
      - recipe[mysql::server]
      - recipe[phpmyadmin::default]
    attributes:
      core:
        common_system: false
        services:
          mysql_admin: {}
      mysql:
        server_root_password: password
      phpmyadmin:
        instances:
          mysql_admin:
            vhost: true

  - name: ssl
    driver:
      network:
        - ["private_network", {ip: "10.10.10.21"}]
    run_list:
      - recipe[core::ssl_certificates]
      - recipe[mysql::server]
      - recipe[phpmyadmin::default]
    attributes:
      core:
        common_system: false
        services:
          mysql_admin: {}
        ssl: true
      mysql:
        server_root_password: password
      phpmyadmin:
        instances:
          mysql_admin:
            ssl: true
            vhost: true
            domain: example.com
      ssl:
        domain: example_com
