#<% require 'kitchen-sync' %>
---
driver:
  name: vagrant
  require_chef_omnibus: 12.3.0

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    driver:
      network:
        - ["private_network", {ip: "10.10.10.20"}]
    run_list:
      - recipe[core::mysql_server]
      - recipe[phpmyadmin::default]
    attributes:
      core:
        common_system: false
        mysql:
          root_password: password
        services:
          mysql_admin: {}
      phpmyadmin:
        instances:
          mysql_admin:
            vhost: true

  - name: ssl
    driver:
      network:
        - ["private_network", {ip: "10.10.10.21"}]
    run_list:
      - recipe[core::ssl_certificates]
      - recipe[core::mysql_server]
      - recipe[phpmyadmin::default]
    attributes:
      core:
        common_system: false
        mysql:
          root_password: password
        services:
          mysql_admin: {}
        ssl: true
      phpmyadmin:
        instances:
          mysql_admin:
            ssl: true
            vhost: true
            domain: example.com
      ssl:
        domain: example_com
