---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    ssl_verify_mode: :verify_peer

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    driver:
      network:
        - ["private_network", {ip: "10.10.10.101"}]
    run_list:
      - recipe[mysql::server]
      - recipe[phpmyadmin::default]
    attributes:
      core:
        common_system: false
        services:
          - name: mysql_admin
      phpmyadmin:
        instances:
          - service: mysql_admin
            action: delete
      mysql:
        server_root_password: password
